# Generated by Django 5.1.1 on 2024-10-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='avatar',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
