# Generated by Django 4.2.16 on 2024-10-27 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='check_birth_year_range',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(('birth_year__gt', 12), ('birth_year__lt', 2024)), name='check_birth_year_range'),
        ),
    ]
