# Generated by Django 5.1.1 on 2024-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
