# Generated by Django 5.1.1 on 2024-10-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow_followee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followee',
        ),
    ]
