# Generated by Django 5.1.1 on 2024-10-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_follow_followee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='followee',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
    ]
