# Generated by Django 5.1.1 on 2024-10-04 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_clap_claps_count_clap_comments_count'),
        ('users', '0006_customuser_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('less_recommend', models.ManyToManyField(blank=True, related_name='less_recommendations', to='articles.article')),
                ('more_recommend', models.ManyToManyField(blank=True, related_name='more_recommendations', to='articles.article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
