# Generated by Django 5.1.1 on 2024-10-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_is_recommend'),
        ('users', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Recommendation',
        ),
    ]
