# Generated by Django 5.1.1 on 2024-10-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_article_topic_alter_recommendation_less_recommend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(related_name='articles', to='users.topic'),
        ),
    ]
