# Generated by Django 5.1.1 on 2024-10-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_is_recommend'),
        ('users', '0013_article_topic_alter_recommendation_less_recommend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='less_recommend',
            field=models.ManyToManyField(blank=True, related_name='less_recommendations', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='more_recommend',
            field=models.ManyToManyField(blank=True, related_name='more_recommendations', to='articles.article'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
