# Generated by Django 5.1.1 on 2024-10-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_follow_followee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='created_at',
        ),
    ]
