# Generated by Django 5.1.1 on 2024-10-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_follow_followee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follow',
        ),
    ]
