# Generated by Django 5.1.1 on 2024-09-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('status', models.SmallIntegerField(choices=[(0, 'Started'), (1, 'Done'), (2, 'Error')])),
                ('thumbnail', models.ImageField(editable=False, upload_to='thumbs')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('midle_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Clap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'topic',
                'ordering': ['name'],
            },
        ),
    ]
