# Generated by Django 5.1.1 on 2024-10-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topics',
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
