# Generated by Django 5.1.1 on 2024-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_topics_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(null=True, related_name='articles', to='articles.topic'),
        ),
    ]
