# Generated by Django 4.2.16 on 2024-10-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_faq_article_archive_article_pinned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pinned',
        ),
    ]
