# Generated by Django 5.1.1 on 2024-10-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_archive_article_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pinned',
        ),
    ]
