# Generated by Django 5.1.1 on 2024-10-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_archive_article_pinned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pin',
        ),
    ]
