# Generated by Django 5.1.1 on 2024-10-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_topic_description_remove_topic_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
