# Generated by Django 5.1.1 on 2024-10-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
