# Generated by Django 5.1.1 on 2024-10-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clap',
            name='claps_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clap',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
