# Generated by Django 5.1.1 on 2024-10-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRASH', 'Trash')], default='ACTIVE', max_length=10),
        ),
    ]
