# Generated by Django 5.1.1 on 2024-10-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('trash', 'TRASH')], default='active', max_length=10),
        ),
    ]
