# Generated by Django 5.1.1 on 2024-10-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
