# Generated by Django 5.1.1 on 2024-10-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_article_is_trashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_trashed',
        ),
    ]
