# Generated by Django 5.1.1 on 2024-10-15 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_rename_favoritearticle_favorite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clap',
            unique_together={('user', 'article')},
        ),
    ]
